sugarlabs/turtleblocksjs

js/activity.js, js/blocks.js
[[PLEASE TEST FIRST, USED DICE.TB AND SOME CARDS.TB FOR TEST.]]
With this patch Turtle Blocks JS, save the collapsed state,
and restore it when you access again to turtleblocks,
also, this patch works with the old data (pre-patch projects.)
=> Save collapsed state of blocks.

js/blocks.js
Steps to reproduce bug (prior to patch):
1. Make a new action
2. Give it a name other than action
3. Open the actions/boxes palette, there will be a pre-made do block
4. Drag out that do block
5. Notice the action name in purple (number)
6. Notice the crash trying to run "NaN"
=> Fix pre-made do blocks expecting numerical action names

js/activity.js, js/blocks.js
Swapping children can have unintended effects, since the previous
top of stack shape can end up anywhere in the z stack!
Steps to reproduce 1 exmaple (before patch):
1. Add a forward block to the start
2. Remove the distance argument block
3. Press run
4. See the error
5. Drag the block
You should see the arrow in a weird Z position.
GCI Task:  http://www.google-melange.com/gci/task/view/google/gci2014/6155168651411456
=> Set Z values, don't swap children

js/blocks.js, js/palette.js
also when you change the name of the action, the palette
block is now updated, the do->oldName block also, is updated to
do->newName
oldname = old action name
newname = new action name.
kudos to walter.
GCI Task: http://www.google-melange.com/gci/task/view/google/gci2014/5878642617876480
=> Remove unused do blocks, when associated action is removed

js/activity.js, js/palette.js
Steps to reproduce (before patch):
1. Try to drag a block into the "start" section
2. Move the start section
3. Notice the blocks did not connect
4. Drag the block again (to the start section)
5. Get annoyed about how it needs 2 drags
=> Dock blocks on initial drag from palette

js/palette.js
Steps to reproduce (before patch):
1. Open a palette
2. Drag out a block
3. Notice: the block is not shown when dragged outside the palette
=> Fix mask when dragging protoblocks

js/activity.js, js/artwork.js, js/palette.js, js/trash.js
First commit:
> **Allow users to drag blocks around the canvas**
>
> Users can now touch-drag on the background to move blocks.  This
> makes it possible to have block stacks larger than the canvas.
2nd commit:
> **Better palette buttons when blocks are below them**
>
> This commit removes the (odd feeling) square background below the
> palette buttons.  The square of blue looks very weird when there are
> block under it.
>
> It also makes the highlight a square, which again looks more natural
> when it is below something.
=> Drag to move blocks

js/palette.js
Tested in Firefox 34 on Fedora 21.  This patch means I can actually use
TurtleBlocks js instead of just staring at the beautiful start block.
=> Actually make the palette - so we can show it instead generating errors

css/activity.css, index.html, js/activity.js, js/block.js, js/blocks.js
* Easier to trigger inputs on touch
* Scale font size and width to canvas scale
* Use input[type=number] so you have a num pad
* Move block to the top of the screen if the person uses touch (so it is
still visible when the viewpoint changes to show the keyboard)
* Don't re-scale when the viewpoint changes during typing because:
* It could just be mobile keyboard popup
* Don't move the block from under the input!
* Delete the input if somebody de-focuses (blurs) it
Sorry, I should have made these into more than 1 of commit :)
=> Refactor the input system

js/block.js
When we hover over a text/number block, label element appears. After changing value of label and without pressing enter, if cursor is hovered on and off the label then the label value toggles between old value and new value.
=> fixed->minor bug in label in block

js/samplesviewer.js
Report: https://markable.in/file/5b2c9fa0-bf7d-11e5-a6fb-0a41a440e2ed.html
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5958307437084672/?sp-page=1
=> Ignoring MusicBlocks_ files from the server when loading up the templates

js/activity.js, js/turtle.js
This is for Google Code-In 2016: eohomegrownapps
After resizing, the turtle now moves to the correct coordinates
on-screen. Any pen strokes the turtle has created will be cleared. As
the pen strokes are stored on the canvas as SVG, resizing them would
either require an overhaul of the entire pen-drawing code or complex
SVG parsing; personally I think neither are worth the effort for the
very small benefit gained as the lines can very easily be redrawn after
resizing the screen by running the turtle blocks. There is a precedent
for this sort of thing - for example the popular maths app GeoGebra
removes the traces points have left after the screen is resized.
=> Fixed bug #258 - Before and after resizing turtle position changes

index.html, js/block.js
OUTDATED: " Chrome has seemed to that some clicks as dragging events. It has been eliminated with adequate workaround - events shorter than 150ms are now never considered dragging events - it doesn't affect usability and comfort. Outdated / unneeded pieces of code has been removed too. "
EDIT: Chrome has seemed to that some clicks as dragging events. It has been eliminated by fixing conditions of @walterbender 's workaround - events shorter than 200ms are now always considered clicks (regardless of movement) - it doesn't affect usability and comfort. `tabindex`es were added to avoid tabbing to the hidden input on mobile devices. 
PR fixes both #237 (we are now able to choose a file on Android) and #275 (error with unchangable text blocks seem to occur never more).
=> Fixed #237 #275; eliminated Chrome related click detection issues

js/utils.js
The camera didn't work on both desktop and Android - the code was obsolete, contained some not useful variables and conditions, it used bad image encoding (`png` is not supported so far). After my fixes, camera works fine on both FF and Chrome (desktop) and Chrome (Android). Safari is currently uncapable of handling camera input with plain HTML5/JS. Additionally, due to the security mechanisms implemented in Chrome on Android, camera can be accessed only when user has established secure connection to the server or server runs on localhost.
=> Fixed #236; made camera working again on both desktop and mobile (Android)

js/block.js
This PR fixes the issue of not being able to drag blocks down from the top of the screen.
My solution to this problem involves setting a minimum y position for a block during drag which is ignored during scrolling since it will be invalid to set a minimum y position for a block during scrolling.
I have chosen (45 * scale) which works perfectly for my computer but needs to be checked for other computer screen combinations. 
This issue is similar to @[https://github.com/walterbender/musicblocks/issues/396](url)
=> Fixes Dragging issue

css/activity.css, index.html, js/status.js
`statusmatrix` had always had visible scrollbar, even while loading. I've changed it to display only when `statusmatrix` is initialized.
=> Fixed #322; scrollbar visible never more during loading

js/logo.js
This PR fixes issue #516 in MB which is necessary in TB as well ; repeat block shows undefined behaviour when it is given a negative number.
Now,TB throws an error when the argument to repeat block is a negative number and skips the repeat block. The error thrown is "Argument must be a positive number".
@walterbender , please review :)
=> Repeat block issue

guide-es/README.md
Currently the images on the Spanish guide are broken and are not being displayed. This fixes the issue.
=> Fix images on the Spanish guide

README.md, documentation/README.md
It turns out this issue was not only on the Spanish guide but on other README.MD files as well.
Note that this is only an issue on the markdown visualization in Github, if you load the index.html pages on each of the folders, they work fine. This branch on our fork displays the images correctly, confirming the fix.
=> Fix broken images on GitHub README.md pages

js/turtle.js
Hi :)
With regard to #276, I have actually found the fix for the SVG output for the Bezier curve, by cleaning up the initial and final svgoutput for Bezier curves. 
Previously, it looks like:
Now, it is rendered correctly:
=> #276: Fixed SVG output for Bezier Curves

plugins/README.md
Earlier it was returning 404 error.
Also there is an image with this link: https://github.com/walterbender/turtleblocksjs/raw/master/screenshots/foodplugin.png
It is causing an 404 error. I can't find this in the repo.
=> Fixed Link

js/block.js
getCacheDataURL method has moved to cache object inside container.
=> fix regression in images due to changes in Easel.js

js/block.js, planet/index.html
Image loading broke in the migration to Easel 1.0
A label was rendered improperly due to the migration to the new Planet server.
=> Fix several regressions due to mirgration

header-icons/fb-inactive.svg, header-icons/planet-disabled-button.svg, js/SaveInterface.js, js/activity.js, js/savebox.js, js/turtledefs.js, js/utils/utils.js
Since the introduction of the new Planet Server, running from file:// has been broken on some browsers. This patch catches all of the planet calls and substitutes local-storage calls where appropriate.
=> run w/o planet

js/activity.js
Somewhat cleaner patch for running from file:///. Also ensures that running from Chrome Server extension still enables access to the Planet server.
=> sync with MB planet code

js/basicblocks.js
Whenever possible, don't reference turtle or mouse so as to keep compatibility between Music Blocks and Turtle Blocks (Impacts calls to Make Block).
=> don't use turtle in block name

js/blocks.js
We were triggering an update of the action palette every time a new block was loaded if there was a calc block in use.
=> avoid unnecessary loading of action palette

js/activity.js, planet/js/GlobalPlanet.js
The GlobalPlanet code assumes that the project ID being loaded matches
one of the card that has been cached. But you can load from an id
passed through the URL via file=ID and there is no guarentee that the
project will be one of the cached projects. This really needs a new
approach to how we handle the cache, but we can manage by ignoring the
cache and just loading the downloaded data.
The GlobalPlanet code has also been reformated to match the style of
the other code in the project.
=> fixed #407 - Work-around for problem loading from planet with file=

js/basicblocks.js
The action blocks were getting cropped when collapsed. By adding some extra width, the problem is solved.
Put x before y on the turtle palette
Put top before bottom and left before right on the media palette
=> fix problem with cropped collapsed action blocks; reorder some palettes

js/basicblocks.js
The default was a palette from Music Blocks, which would be confusing to Turtle Blocks users.
=> use Turtle as default palette to open

js/artwork.js
On hovering the icons at the top left corner the circle was not enclosing the
icons.
Changing the coordinates of the centre of the circle in artwork.js fixed the
issue.
Fixes https://github.com/sugarlabs/turtleblocksjs/issues/447
=> Fixing icon on hover issue.

package-lock.json, package.json
This PR removes the `lodash.template` dependency .
- Removed `lodash.template` from `package.json`.
- Verified that `gulp-util` is not directly used in the project.
- [Command Injection in lodash.template](https://github.com/advisories/GHSA-35jh-r3h4-6jhm)
=> remove lodash dependencies
