- js/samplesviewer.js
:) Right or down for next page
:) Left or up for prev page
> Add swipe gesture to sample viewer.

- js/activity.js
- js/blocks.js
- js/turtle.js
Update container cache, in setheading.
> Save state of turtles.

- js/activity.js
- js/advancedblocks.js
Ignacio's blocks looked lonely :smiley_cat:
> Add Weather Mashape blocks

- js/activity.js
> Only show the example from web button if you can access to server

- index.html
> Fix some typos in the tour

- js/activity.js
- js/palette.js
- js/utils.js
GCI task:  http://www.google-melange.com/gci/task/view/google/gci2014/5822163865042944
> Delete plugins by dragging palettes to trash

- js/activity.js
Fix the wrong style code, and also, dont calculate scale, use the same of the canvas
> Tour improvements

- js/turtle.js
GCI Task:  http://www.google-melange.com/gci/task/view/google/gci2014/5898558582554624
> Allow users to rotate the turtle by double clikcing and draging

- NEWS
- js/activity.js
Now, we can open the same file :smile_cat:
> set the value of chooser to null, when it's opened

- js/activity.js
- js/artwork.js
- js/basicblocks.js
- js/blocks.js
Example (I would include a .tb, but there is no save to file in master :disappointed:):
GCI Task: http://www.google-melange.com/gci/task/view/google/gci2014/5263066228850688
> Wait For Block

- js/palette.js
GCI Task: http://www.google-melange.com/gci/task/view/google/gci2014/5844300596248576
> Clean up palette buttons layout after remove a plugin

- js/activity.js
Made code more 'readable'  and use the x,y of container.
> fixes to pixel block

- index.html
- js/activity.js
> Fix scaling on small screens to make blocks a better size

- js/activity.js
- js/palette.js
- js/utils.js
Have I got the scroll wheel scroll the right way round?  I not 100% sure.
Anyway, the touch and drag to scroll seems to be the right way :)
> Scroll the palette icons if there is an overflow

- js/palette.js
> width of palette toolbars adapted to palette columns

- index.html
- js/palette.js
* Use the masks
* Fix issues where you are prevented from scrolling
> Menu scroll++

- js/activity.js
> Mouse X, mouse Y works again

- NEWS
- js/activity.js
only enable drag and drop of all blocks when turtles are not running, also now the mouse button block works
> mouse button block works again

- js/activity.js
- js/utils.js
* Don't re-rotate the menu icon if it is already down
* Use localstorage, cordova doesn't do cookies
> Fix a few bugs with the tour

- js/block.js
- js/palette.js
Steps to reproduce (before patch):
1. Drag a setxy block into the start section
2. Replace the top argument with a plus block
3. Notice the start section doesn't expand
> When block is expanded, change block.size so colapsiable blocks expand

- js/blockfactory.js
> Add shadow to blocks

- js/block.js
> Fix over-sizing of loops

- js/activity.js
- js/palette.js
> Get the z-ordering right

- po/it.po
> Updated it.po file.

- index.html
- js/activity.js
- js/samplesviewer.js
> More material design

- js/palette.js
It doesn't fix all of them, but this is an improvement
> Fix palette scale issues

- js/palette.js
faded down button was not getting to correct position after resizing the palette.
> a small fix in resizing palette

- js/activity.js
- js/basicblocks.js
- js/block.js
- js/blockfactory.js
- js/blocks.js
- js/clearbox.js
- js/logo.js
- js/munsell.js
- js/palette.js
- js/pluginsviewer.js
- js/protoblocks.js
- js/samplesviewer.js
- js/turtle.js
- js/utilitybox.js
- js/utils.js
replaced "==" with "===" and "!=" with "!=="
Might improve speed a little bit.
Part of GCI2015 contest.
> replaced equal signs with their strict equal alternatives

- js/basicblocks.js
- js/logo.js
- js/turtle.js
* New block for pen transparency: 100=Invisible, 0=Totally visible
* This is a GCI 2015 task: https://codein.withgoogle.com/tasks/5259867971387392/
> Added "set translucency" block

- js/activity.js
- js/blocks.js
- js/logo.js
> fixes #259

- js/artwork.js
- js/trash.js
Size of trash area is now 
Width : 260
Height : 70
> Samller trash area

- js/activity.js
> updated it v2.8

- header-icons/fb-inactive.svg
- header-icons/fb.svg
- header-icons/save-png.svg
- header-icons/save-svg.svg
- header-icons/save-tb.svg
- header-icons/upload-planet.svg
- js/activity.js
- js/savebox.js
Created drop down menu on 'Save Project' button, saves different file extensions for project.
> save as changes

- js/activity.js
Error messages will automatically disappear after 10 seconds if they are not pressed by user.
> Make error messages autodisappearing after 10secs

- header-icons/save-png-inactive.svg
- js/activity.js
- js/savebox.js
1) SVG functionality fixed
2) PNG disabled for now
> Save enhancement update1

- plugins/length_converter.json
- plugins/length_converter.rtp
> New plugin added

- js/palette.js
- js/utils.js
Per analogy to https://github.com/walterbender/musicblocks/pull/478
> Require palette labels to be written with title case

- js/clearbox.js
Per analogy to https://github.com/walterbender/musicblocks/pull/488
> Fixed reference error breaking delete all feature

- js/block.js
- js/palette.js
- js/trash.js
Per analogy to https://github.com/walterbender/musicblocks/pull/486
> Added trash animation

- js/protoblocks.js
Per https://github.com/walterbender/musicblocks/pull/504
> Fixed waitFor connections and size issues

- js/activity.js
Per https://github.com/walterbender/musicblocks/pull/507
> Removed unused stop function from activity.js

- js/analytics.js
- js/basicblocks.js
- js/logo.js
- js/status.js
This PR adds 'Raised to the power of' block to the Number palette.
> Raised to the power of block added

- js/basicblocks.js
The SVG processing has changed. ">" and "<" will work now.
> &gt; --> >

- js/activity.js
- js/basicblocks.js
FIxes load/save of named args.
> fix typo that breaks named args

- js/activity.js
The download function was moved to save.
> fix regression in save block svg

- guide/README.md
- js/basicblocks.js
- js/block.js
- js/logo.js
- js/macros.js
- planet/index.html
Revert inadvertent changes to macros, basic blocks. Update example URLs in Guide to point to planet projects.
> More cleanup from planet conversion

- guide/README.md
- header-icons/go-home-button.svg
- header-icons/go-home-faded-button.svg
- js/activity.js
- js/basicblocks.js
- js/block.js
- js/logo.js
- js/macros.js
- js/turtledefs.js
- planet/index.html
* Update Home icon
* Restore instead of Undo
> more changes from Music Blocks

- js/activity.js
the dataURL is only available from the cache
> fix regression due to Easel upgrade

- js/macros.js
- js/widgets/status.js
Lots of changes had not been migrated from Music Blocks;
The hidden flow block was missing from the macro, causing it to not trigger its close event
> fix regression in status block

- guide/index.html
- js/macros.js
- js/widgets/status.js
The index.html file was woefully out of date.
> Update to latest MD content

- js/basicblocks.js
- js/block.js
- js/blocks.js
- js/logo.js
- js/palette.js
- js/utils/utils.js
Similar to a change in Music Blocks, this series of patches enables longer names for actions and text blocks.
> expand nameddo and text blocks to contain longer labels

- js/basicblocks.js
- js/block.js
- js/blocks.js
- js/logo.js
- js/palette.js
- js/turtle.js
- js/utils/utils.js
Longer labels are especially important in languages such as Japanese.
> more label adjustments

- js/basicblocks.js
Was added to Music Blocks but never added here.
> add comment block

- js/basicblocks.js
Not paying attention. print --> comment
> fix error in comment block

- js/basicblocks.js
- js/logo.js
- js/macros.js
- js/palette.js
* Add new block, Set Turtle, which will run a stack of blocks under the turtle specified
* Migrate Make block functionality from Music Blocks
* Add special glue to enable proper handling of Run block for Start blocks.
> add set turtle block

- js/basicblocks.js
- js/logo.js
A boolean block to know whether or not a turtle is available... useful in scenarios such as:
> Add found turtle block

- js/basicblocks.js
- js/logo.js
Allow for integer turtle names; new turtle block as short cut to generating new turtles with make block.
> More tweaks to multi-turtle code

- guide/README.md
Point to the new turtle example on the planet
> add RUN LIVE link

- guide/README.md
- guide/extras3.svg
- js/logo.js
Since the *New Turtle* block returns before the new turtle is launched (so as to avoid blocking), an event is dispatched to indicate that the turtle is available.
> Broadcast an event when creating a new turtle

- js/activity.js
- js/logo.js
We were triggering loadingifnished event handlers inadvertently.
> clean up event handlers after load

- js/basicblocks.js
Missing number block from number menu has been added.
> added missing abs block in number menu

- js/activity.js
- js/blocks.js
These files get too large with Turtle and they have limited utility. (In Music Blocks, they are needed for performance purposes.)
> Don't save compiled playback code for TB

- js/activity.js
The handler for the stagemousemove was getting lost. Now it is added each time the run button is pressed.
> fixes cursor freeze issue (MB #1130)

- js/logo.js
> add comment output to console

- js/activity.js
- js/logo.js
merging MB commit to TB version
> sync with MB commit

- guide/Confusion.md
- js/activity.js
* Don't erase the playback data when saving project.
* Add keyboard shortcut Alt-P to documentation (redisplay challenge)
> more fine-tuning in support of Turtle Confusion

- README.md
fixed linked to raw Github file to download plugin in JSON.
> fixed plugin links in readme

- guide/README.md
fixed link to example in planet
> fixed statusblock example

- js/SaveInterface.js
- js/basicblocks.js
- js/block.js
- js/blocks.js
- js/logo.js
- js/utils/utils.js
(1) use turtle as default palette
(2) fix read pixel bug
(3) fix input bug on FF
> several fixes

- js/SaveInterface.js
- js/basicblocks.js
- js/block.js
- js/blocks.js
- js/logo.js
- js/utils/utils.js
The gist is a series of changes to the way input value is handled to work around issues with FF
> more updates from MB

- README.md
As part of my [GCI task](https://codein.withgoogle.com/dashboard/task-instances/5420843031592960/) - Turtle Blocks Issue: Change the readme images to the new UI
I added a new Gif in the screenshots folder. I have a couple of doubts, do we have to remove the screenshot which are not used anymore.
For updating the icons which are present in the Readme should i take screenshots or what is the right approach.
@walterbender @vaibhavdaren @ezequielpereira
> Updated Readme with new images

- plugins/random_quote.json
#456 
@nepaltechguy2 is almost done a rewrite of planet and he is planning to add an endpoint where we can fetch quotes from. This is just a temporary fix for now showing how we will use his endpoint, but once he finishes setting up his plant server it's just a matter of changing the URL.
> fix quote block

- css/activities.css
- js/palette.js
fixes: #451 
Added scrollbar as shown:
https://user-images.githubusercontent.com/86892991/148105133-a443d354-eb2a-4c3d-9c4b-888c1faf0e19.mp4
> Added scrollbar to block windows

- .gitignore
- gulpfile.js
- header-icons/restore-from-trash.svg
- header-icons/wrap-text.svg
- package-lock.json
- package.json
This PR addresses two critical updates:
1. **Dependency Updates:** Modernizes outdated dependencies to ensure compatibility and maintainability.
2. **Icons Addition:** Adds missing icons to enhance UI/UX consistency. As seen here:
---
- Replaced the deprecated `gulp-minify-css` with `gulp-clean-css`.
- Removed the deprecated `gulp-util` and replaced it with individual utilities.
- Updated `gulpfile.js` to use `gulp-clean-css` instead of `gulp-minify-css`.
- Updated `package.json` to reflect these dependency changes.
- Resolved missing icons issue by adding relevant assets to ensure consistent UI elements.
---
- Tested the project build process to ensure compatibility with the updated dependencies ran npm run serve.
- Confirmed that the added icons render correctly in the affected UI …
> Fix: Update Dependencies and Add Missing Icons
